name: "Questionnaire Sdk"
on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
jobs:

  publish-to-github-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Github Env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate Secretes File
        run: |
          touch gradle.properties
          echo "" >> gradle.properties
          echo "gpr.user=${{ secrets.GRADLE_USERNAME }}" >> gradle.properties
          echo "gpr.key=${{ secrets.GRADLE_KEY }}" >> gradle.properties
          echo "tag.version=${{ env.RELEASE_VERSION }}" >> gradle.properties

      - name: Show Gradle Properties
        run: cat gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2

      - name: Publish JVM To Github Packages
        run: ./gradlew publish

